### ISSUE TITLE
JDNConvertibleCalendarDateAdapter not compatible with angular 10

### ISSUE THREAD

**Issue by Lexa950609** [dhlab-basel/JDNConvertibleCalendarDateAdapter#24]
I got this error while tying to update my angular 9 project to angular 10. 

 Package "jdnconvertiblecalendardateadapter" has an incompatible peer dependency to "@angular/material" (requires "^9.2.1", would install "10.2.0").

**Comment by tobiasschweizer** [comment]
Yes, I still have to provide and publish a version for Angular 10. I think that will happen soon. Shall I give you a notification once it is done?

I think I should also improve the documentation so it becomes clear which Angular version this lib is compatible with. The README is most likely out of date.

Also I need to make a new version of jdnconvertiblecalendar since the current version uses [commonjs module](https://github.com/dhlab-basel/JDNConvertibleCalendar/blob/76cd95fe06a9ae329d00cc75f7e5d688c32cc161/tsconfig.json#L4) which will throw a warning with Angular 10.

**Comment by Lexa950609** [comment]
Okay thank you.. Do you have any idea how long will it take you to publish it?

**Comment by tobiasschweizer** [comment]
I cannot make any promises but I will try to do it within the next two weeks. The thing is that first I would have to make a new version of jdnconvertiblecalendar with different build options (see https://blog.angular.io/version-10-of-angular-now-available-78960babd41 section Warnings about CommonJS imports).

**Comment by tobiasschweizer** [comment]
@Gayashani95 I have just published version 0.0.14. Could you try it?

Please be aware that when building the app, you will get a warning like:

> WARNING in ../JDNConvertibleCalendarDateAdapter/dist/jdnconvertible-calendar-date-adapter/__ivy_ngcc__/fesm2015/jdnconvertiblecalendardateadapter.js depends on 'jdnconvertiblecalendar'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

We are working on a new [version](https://github.com/dhlab-basel/JDNConvertibleCalendar/pull/23) of `jdnconvertiblecalendar` but this needs some more time.

You can [disable](https://github.com/appvision-gmbh/json2typescript/issues/147#issuecomment-688687115) these warnings for now.

**Comment by Lexa950609** [comment]
Thank you so much for the great support you have provided.. And Yes!! now
the issue is solved i was having previously with the library. Anyway thanks
again for the quick response..
Waiting for the new release of JDNConvertibleCalender library too.
Have a nice day!
